[package]
name = "net_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
arbitrary = "1.2.0"
clap = { version = "4.0.29", features = ["derive"] }
heapless = { version = "0.7.16", default-features = false, features = ["serde"] }
postcard = { version = "1.0.2", features = ["use-std"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.149", features = ["derive"] }

[profile.release]
debug = true
