[package]
name = "net-finder-fpga-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
net-finder = { path = "../..", features = ["no-trie"] }
event-listener = "5.3.1"

[build-dependencies]
anyhow = "1.0.79"
cc = "1.0.83"
