[package]
name = "net-finder-cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
indicatif = "0.17.7"
net-finder = { path = "../.." }
rayon = "1.8.1"
