[project]
name = "net-finder-soc"
version = "0.1.0"
dependencies = [
    "migen",
    "litedram",
    "liteeth",
    "litepcie",
    "litescope",
    "litex",
    "litex-boards",
    "pythondata-cpu-vexriscv",
    "pythondata-misc-tapcfg",
    "pythondata-software-picolibc",
    "pythondata-software-compiler-rt",
    "dearpygui",
    "pyvcd",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
