name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_cpu:
    name: Test net-finder-cpu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo run --release -p net-finder-cpu 1x1x5 1x2x3
      - run: test "$(cat state/1x1x5,1x2x3.json | jq '.solutions | length')" = 2263
  test_soc:
    name: Test SoC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install verilator libevent-dev libjson-c-dev
      - run: pip install -r requirements.txt
      - run: |
          python3 -m net_finder.soc.sim --cuboids 1x1x5 1x2x3 --non-interactive &
          while ! nc -z localhost 1111; do
            sleep 1
          done

          litex_server --uart --uart-port socket://127.0.0.1:1111 &
          while ! nc -z localhost 1234; do
            sleep 1
          done

          cargo run -p net-finder-fpga-driver -- --addr 127.0.0.1:1234 --tcp sim_soc_info.json

          kill %2
          kill %1
      - run: test "$(cat state/1x1x5,1x2x3.json | jq '.solutions | length')" = 2263
